[2025-03-03T04:00:06.770+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T04:00:06.781+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_data scheduled__2025-03-03T03:00:00+00:00 [queued]>
[2025-03-03T04:00:06.791+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_data scheduled__2025-03-03T03:00:00+00:00 [queued]>
[2025-03-03T04:00:06.793+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T04:00:06.837+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_data> on 2025-03-03 03:00:00+00:00
[2025-03-03T04:00:06.854+0000] {standard_task_runner.py:72} INFO - Started process 773 to run task
[2025-03-03T04:00:06.860+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'download_data', 'scheduled__2025-03-03T03:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpwt6s1mc1']
[2025-03-03T04:00:06.864+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask download_data
[2025-03-03T04:00:06.913+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:00:06.972+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.download_data scheduled__2025-03-03T03:00:00+00:00 [running]> on host b5502d51568b
[2025-03-03T04:00:06.977+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T04:00:07.121+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T03:00:00+00:00'
[2025-03-03T04:00:07.123+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T04:00:07.150+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_acquisition.py
[2025-03-03T04:00:08.160+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/data_acquisition.py: Command '['python', '/opt/airflow/scripts/data_acquisition.py']' returned non-zero exit status 1.
[2025-03-03T04:00:08.164+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T04:00:08.173+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T04:00:08.175+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_data, run_id=scheduled__2025-03-03T03:00:00+00:00, execution_date=20250303T030000, start_date=20250303T040006, end_date=20250303T040008
[2025-03-03T04:00:08.254+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T04:00:08.278+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T04:00:08.285+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
