[2025-03-03T02:28:36.892+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:28:36.926+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.upload_to_gcs manual__2025-03-03T02:27:03.423548+00:00 [queued]>
[2025-03-03T02:28:36.943+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.upload_to_gcs manual__2025-03-03T02:27:03.423548+00:00 [queued]>
[2025-03-03T02:28:36.947+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:28:36.979+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_to_gcs> on 2025-03-03 02:27:03.423548+00:00
[2025-03-03T02:28:36.996+0000] {standard_task_runner.py:72} INFO - Started process 352 to run task
[2025-03-03T02:28:37.001+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'upload_to_gcs', 'manual__2025-03-03T02:27:03.423548+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpbg1lb52q']
[2025-03-03T02:28:37.012+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask upload_to_gcs
[2025-03-03T02:28:37.044+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:28:37.126+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.upload_to_gcs manual__2025-03-03T02:27:03.423548+00:00 [running]> on host b5502d51568b
[2025-03-03T02:28:37.232+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T02:27:03.423548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T02:27:03.423548+00:00'
[2025-03-03T02:28:37.235+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:28:37.266+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/upload_to_gcs.py
[2025-03-03T02:28:39.423+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/upload_to_gcs.py: Command '['python', '/opt/airflow/scripts/upload_to_gcs.py']' returned non-zero exit status 1.
[2025-03-03T02:28:39.425+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:28:39.437+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:28:39.441+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=upload_to_gcs, run_id=manual__2025-03-03T02:27:03.423548+00:00, execution_date=20250303T022703, start_date=20250303T022836, end_date=20250303T022839
[2025-03-03T02:28:39.512+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:28:39.554+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:28:39.563+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
