[2025-03-02T20:09:46.185+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T20:09:46.199+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-03-02T19:00:00+00:00 [queued]>
[2025-03-02T20:09:46.207+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-03-02T19:00:00+00:00 [queued]>
[2025-03-02T20:09:46.207+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-02T20:09:46.223+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_dvc_pipeline> on 2025-03-02 19:00:00+00:00
[2025-03-02T20:09:46.228+0000] {standard_task_runner.py:72} INFO - Started process 765 to run task
[2025-03-02T20:09:46.231+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'run_dvc_pipeline', 'scheduled__2025-03-02T19:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpoyphk3dp']
[2025-03-02T20:09:46.233+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask run_dvc_pipeline
[2025-03-02T20:09:46.247+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T20:09:46.269+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-03-02T19:00:00+00:00 [running]> on host 150a7fb033c6
[2025-03-02T20:09:46.271+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-02T20:09:46.336+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='run_dvc_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T19:00:00+00:00'
[2025-03-02T20:09:46.337+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T20:09:46.350+0000] {data_pipeline.py:51} INFO - Executing script: /opt/airflow/scripts/dvc_pipeline.py
[2025-03-02T20:09:48.407+0000] {data_pipeline.py:55} ERROR - Error executing /opt/airflow/scripts/dvc_pipeline.py: Command '['python', '/opt/airflow/scripts/dvc_pipeline.py']' returned non-zero exit status 1.
[2025-03-02T20:09:48.408+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T20:09:48.413+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T20:09:48.413+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=run_dvc_pipeline, run_id=scheduled__2025-03-02T19:00:00+00:00, execution_date=20250302T190000, start_date=20250302T200946, end_date=20250302T200948
[2025-03-02T20:09:48.491+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T20:09:48.502+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T20:09:48.503+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
