[2025-03-04T04:03:42.187+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T04:03:42.213+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-03-04T03:00:00+00:00 [queued]>
[2025-03-04T04:03:42.226+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-03-04T03:00:00+00:00 [queued]>
[2025-03-04T04:03:42.227+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-04T04:03:42.263+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_dvc_pipeline> on 2025-03-04 03:00:00+00:00
[2025-03-04T04:03:42.274+0000] {standard_task_runner.py:72} INFO - Started process 2743 to run task
[2025-03-04T04:03:42.279+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'run_dvc_pipeline', 'scheduled__2025-03-04T03:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpmeye0dl1']
[2025-03-04T04:03:42.285+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask run_dvc_pipeline
[2025-03-04T04:03:42.319+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-04T04:03:42.389+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.run_dvc_pipeline scheduled__2025-03-04T03:00:00+00:00 [running]> on host b5502d51568b
[2025-03-04T04:03:42.393+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-04T04:03:42.537+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='run_dvc_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-04T03:00:00+00:00'
[2025-03-04T04:03:42.540+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T04:03:42.579+0000] {data_pipeline.py:51} INFO - Executing script: /opt/airflow/scripts/dvc_pipeline.py
[2025-03-04T04:03:44.252+0000] {data_pipeline.py:55} ERROR - Error executing /opt/airflow/scripts/dvc_pipeline.py: Command '['python', '/opt/airflow/scripts/dvc_pipeline.py']' returned non-zero exit status 1.
[2025-03-04T04:03:44.254+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-04T04:03:44.270+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T04:03:44.272+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=run_dvc_pipeline, run_id=scheduled__2025-03-04T03:00:00+00:00, execution_date=20250304T030000, start_date=20250304T040342, end_date=20250304T040344
[2025-03-04T04:03:44.343+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T04:03:44.370+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T04:03:44.372+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
