[2025-03-03T02:13:08.333+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:13:08.372+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.generate_schema_statistics manual__2025-03-03T01:53:22.667705+00:00 [queued]>
[2025-03-03T02:13:08.393+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.generate_schema_statistics manual__2025-03-03T01:53:22.667705+00:00 [queued]>
[2025-03-03T02:13:08.401+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:13:08.459+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): generate_schema_statistics> on 2025-03-03 01:53:22.667705+00:00
[2025-03-03T02:13:08.480+0000] {standard_task_runner.py:72} INFO - Started process 395 to run task
[2025-03-03T02:13:08.485+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'generate_schema_statistics', 'manual__2025-03-03T01:53:22.667705+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpbd19kgl7']
[2025-03-03T02:13:08.489+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask generate_schema_statistics
[2025-03-03T02:13:08.524+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:13:08.575+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.generate_schema_statistics manual__2025-03-03T01:53:22.667705+00:00 [running]> on host 71fb9604a64f
[2025-03-03T02:13:08.687+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='generate_schema_statistics' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T01:53:22.667705+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T01:53:22.667705+00:00'
[2025-03-03T02:13:08.692+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:13:08.721+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_schema_statistics.py
[2025-03-03T02:13:08.790+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/data_schema_statistics.py: Command '['python', '/opt/airflow/scripts/data_schema_statistics.py']' returned non-zero exit status 2.
[2025-03-03T02:13:08.793+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:13:08.806+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:13:08.808+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=generate_schema_statistics, run_id=manual__2025-03-03T01:53:22.667705+00:00, execution_date=20250303T015322, start_date=20250303T021308, end_date=20250303T021308
[2025-03-03T02:13:08.866+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:13:08.904+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:13:08.913+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
