[2025-03-03T02:12:59.905+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-03T02:12:59.932+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.generate_schema_statistics scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-03-03T02:12:59.952+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.generate_schema_statistics scheduled__2025-03-03T00:00:00+00:00 [queued]>
[2025-03-03T02:12:59.955+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-03T02:12:59.987+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): generate_schema_statistics> on 2025-03-03 00:00:00+00:00
[2025-03-03T02:13:00.001+0000] {standard_task_runner.py:72} INFO - Started process 379 to run task
[2025-03-03T02:13:00.007+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'generate_schema_statistics', 'scheduled__2025-03-03T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpieixcz1f']
[2025-03-03T02:13:00.012+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask generate_schema_statistics
[2025-03-03T02:13:00.042+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:13:00.085+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.generate_schema_statistics scheduled__2025-03-03T00:00:00+00:00 [running]> on host 71fb9604a64f
[2025-03-03T02:13:00.088+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T02:13:00.195+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='generate_schema_statistics' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T00:00:00+00:00'
[2025-03-03T02:13:00.197+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-03T02:13:00.235+0000] {data_pipeline.py:63} INFO - Running script: /opt/airflow/scripts/data_schema_statistics.py
[2025-03-03T02:13:00.371+0000] {data_pipeline.py:67} ERROR - Error executing /opt/airflow/scripts/data_schema_statistics.py: Command '['python', '/opt/airflow/scripts/data_schema_statistics.py']' returned non-zero exit status 2.
[2025-03-03T02:13:00.380+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-03T02:13:00.408+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-03T02:13:00.412+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=generate_schema_statistics, run_id=scheduled__2025-03-03T00:00:00+00:00, execution_date=20250303T000000, start_date=20250303T021259, end_date=20250303T021300
[2025-03-03T02:13:00.507+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-03T02:13:00.546+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-03T02:13:00.568+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
